# Generated by Django 3.0.4 on 2020-06-04 07:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('lesson_title', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=10)),
                ('lesson_description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModal',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers_profiles/')),
                ('mobile', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('staff_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_picture', models.ImageField(blank=True, null=True, upload_to='stubject_images/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ClassRoom')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.TeacherModal')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ClassRoom')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.TeacherModal')),
            ],
        ),
        migrations.CreateModel(
            name='LessonFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_files/')),
                ('type', models.CharField(max_length=10)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject'),
        ),
    ]
