# Generated by Django 3.0.4 on 2020-06-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodal',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='teachers_profiles/'),
        ),
    ]
