# Generated by Django 3.0.4 on 2020-06-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200612_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=15),
        ),
    ]
