# Generated by Django 3.0.4 on 2020-06-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200612_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15),
        ),
    ]
